version: 2

node-build: &node-build
  working_directory:  ~/repo
  docker:
    - image: circleci/node:10.15.3

attach_root_workspace: &attach_root_workspace
  attach_workspace:
    at: .

jobs:

  fetch_dependencies:
    <<: *node-build

    steps:
      - checkout

      - *attach_root_workspace

      - run:
          name: Login into Github package registry
          command: |
            sudo npm i -g npm-cli-login
            npm-cli-login

      - run:
          name: Install dependencies
          command: npm ci

      # Disable until a fix available for `acorn` package.
      #- run:
      #    # Here I move .npmrc to allow audit (GH registry doesn't support audit for now)
      #    name: Audit dependencies
      #    command: |
      #      mv .npmrc .npmrc.old
      #      npm audit
      #      mv .npmrc.old .npmrc

      - persist_to_workspace:
          root:  .
          paths:
            - .

  publish:
    <<: *node-build

    steps:
      - *attach_root_workspace

      - run:
          name: Publish @amplement/pm2-gelf-pro
          command: |
            sudo npm i -g npm-cli-login
            npm-cli-login
            # fix for publishing
            echo "registry=https://npm.pkg.github.com/amplement" > .npmrc
            npm publish

workflows:
  version: 2
  complete-workflow:
    jobs:
      - fetch_dependencies:
          context: org-global
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*/
      - publish:
          context: org-global
          requires:
            - fetch_dependencies
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*/
